[build]
  command = "ng build && cp db.json dist/app-alunos/db.json"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/app-alunos/db.json"
  status = 200
